### ISSUE TITLE
Sort by Price shows different collection to other sort options

### ISSUE THREAD

**Issue by harrigo** [manadev/manadev-layered-nav-multiple-select-for-magento#4]
Sort by Price shows different collection to other sort options have attached some logs.

Issue occurs as soon as i enable this plugin but only seems to happen within search.

[fc-name.log](https://github.com/manadev/manadev-layered-nav-multiple-select-for-magento/files/1391675/fc-name.log)
[fc-price.log](https://github.com/manadev/manadev-layered-nav-multiple-select-for-magento/files/1391676/fc-price.log)
[pc-name.log](https://github.com/manadev/manadev-layered-nav-multiple-select-for-magento/files/1391677/pc-name.log)
[pc-price.log](https://github.com/manadev/manadev-layered-nav-multiple-select-for-magento/files/1391678/pc-price.log)

**Comment by harrigo** [comment]
Sorry this issue applies to the magento 2 version of the plugin which does not seem to be on github?

**Comment by vo-manadev** [comment]
Magento 2 version is not on Github. It is available here: https://www.manadev.com/layered-navigation-filters-multiple-select-magento-2

**Comment by harrigo** [comment]
Ok was having issues on this not working with Magneto 2.2.x with search "Property order does not exist" error. Just wanted to post the issue somewhere but I have created a workaround for this now.
