### ISSUE TITLE
price is 1 unit range

### ISSUE THREAD

**Issue by gh-darvishani** [manadev/manadev-layered-nav-multiple-select-for-magento#6]
Hi
on your module price rang is one unit for example 
1$-2$
5$-6$
8$-9$
how we can change this or where we going wrong that show like this ?

**Comment by vo-manadev** [comment]
Hi,

Most probably there is price range step set in Magento Admin Panel. You can
change it either

1, Globally, in System->Configuration->Catalog->Layered Navigation, set
Price Navigation Step Calculation = Manual and Default Price Navigation
Step = 100 or
2. For specific category, in Catalog->Manage Categories->[your
category]->Display Settings->Layered Navigation Price Step = 100.

Hope this helps.

**Comment by gh-darvishani** [comment]
thanks but i did not see any Layered Navigation on Configuration !!
are you sure  ? or maybe i should change  code ?
look at this directory ... if your module have any configuration part that should see at last one system.xml file
https://github.com/manadev/manadev-layered-nav-multiple-select-for-magento/blob/master/code/etc/

**Comment by vo-manadev** [comment]
It is not our module configuration, it is standard Magento configuration,
please review previous answer once again for exact location of settings in
Admin Panel

**Comment by gh-darvishani** [comment]
you are right ...thanks  a lot
